_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 128
dropout:
    value: 0.7237396843598951
epochs:
    value: 5
lr:
    value: 0.001
